import os
import glob
import logging
from flask import (
    Blueprint, send_file, render_template_string, render_template, 
    redirect, url_for, request, flash, jsonify
)
from flask_login import login_required, logout_user, current_user, login_user
from core_app.forms import LoginForm
from core_app.models import User
from dotenv import load_dotenv

routes_bp = Blueprint('routes', __name__)
load_dotenv()

# System State
MAINTENANCE_MODE = False

# --- Logging Configuration ---
LOG_FILE_PATH = os.getenv('APP_LOG_FILE', 'app_activity.log')

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(LOG_FILE_PATH),
        logging.StreamHandler()
    ]
)

logger = logging.getLogger(__name__)

# ==============================================================================
# Helper Logic
# ==============================================================================

def find_most_recent_processed_map():
    """Locates the latest HTML map file generated by the monitor service."""
    # Maps are expected to follow the pattern 'map_YYYYMMDD_HH.html'
    map_output_dir = os.getenv('MAP_OUTPUT_DIR', '/tmp')
    map_pattern = os.path.join(map_output_dir, 'map_*.html')
    list_of_maps = glob.glob(map_pattern)
    
    if not list_of_maps:
        return None

    try:
        # Sort by modification time to retrieve the latest one
        latest_map = max(list_of_maps, key=os.path.getmtime)
        return latest_map
    except Exception as e:
        logger.error(f"Error searching for the latest processed map: {e}")
        return None

# ==============================================================================
# Authentication Routes
# ==============================================================================

@routes_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('routes.show_latest_map_or_status'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password.', 'danger')
            logger.warning(f"Failed login attempt for user: {form.username.data}")
            return redirect(url_for('routes.login'))

        login_user(user, remember=form.remember_me.data)
        logger.info(f"User {user.username} logged in successfully.")

        next_page = request.args.get('next')
        if not next_page or not next_page.startswith('/'):
            next_page = url_for('routes.show_latest_map_or_status')
        return redirect(next_page)
        
    return render_template('login.html', title='Hurakan - Login', form=form)

@routes_bp.route('/logout')
@login_required
def logout():
    logger.info(f"User {current_user.username} logged out.")
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('routes.login'))

# ==============================================================================
# Main Application Routes
# ==============================================================================

@routes_bp.route('/')
@login_required
def show_latest_map_or_status():
    if MAINTENANCE_MODE:
        return render_template('maintenance.html')
    
    latest_processed_map = find_most_recent_processed_map()

    if latest_processed_map and os.path.exists(latest_processed_map):
        logger.info(f"Serving latest map: {os.path.basename(latest_processed_map)}")
        return send_file(latest_processed_map)
    else:
        logger.warning("No processed HTML maps found in output directory.")
        error_html = """
            <html><head><title>No Maps Available</title>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
            <style> 
                body { font-family: sans-serif; display: flex; flex-direction: column; 
                       align-items: center; justify-content: center; height: 90vh; color: #6c757d; } 
                .icon { font-size: 3em; margin-bottom: 20px; } 
            </style>
            </head><body>
            <i class="fas fa-map-marker-alt icon"></i>
            <h2>No Maps Available</h2>
            <p>The system is waiting for new data or initial processing. Please try again in a few minutes.</p>
            </body></html>
            """
        return render_template_string(error_html), 503

@routes_bp.route('/upload_map', methods=['POST'])
def upload_map():
    """Endpoint for the monitor service to upload combined HTML maps."""
    if 'map_file' not in request.files:
        logger.error("Missing 'map_file' in upload request.")
        return jsonify(message="No map file provided"), 400

    map_file = request.files['map_file']
    if map_file.filename == '':
        logger.error("Empty filename in upload request.")
        return jsonify(message="Empty map filename"), 400

    try:
        map_output_dir = os.getenv('MAP_OUTPUT_DIR', '/tmp')
        save_path = os.path.join(map_output_dir, map_file.filename)
        map_file.save(save_path)
        logger.info(f"Map '{map_file.filename}' saved successfully to {save_path}")
        return jsonify(message=f"Map '{map_file.filename}' received successfully"), 200
    except Exception as e:
        logger.error(f"Error saving uploaded map '{map_file.filename}': {e}", exc_info=True)
        return jsonify(message=f"Error saving map: {str(e)}"), 500

@routes_bp.route('/health')
def health_check():
    """Basic health check endpoint for the Flask application."""
    try:
        return jsonify(status="OK"), 200
    except Exception as e:
        logger.error(f"Health check failed: {e}")
        return jsonify(status="ERROR", reason=str(e)), 503